compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [arm64, x64]
  libc: [glibc]

yarnPath: .yarn/releases/yarn-4.3.0.cjs
