name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release Package to NPM and GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup registry url with NPM
        uses: actions/setup-node@v4.4.0
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: package.json
      - run: yarn install --immutable
      - run: yarn run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Rename before Publish to GitHub Packages
        uses: mikefarah/yq@v4.46.1
        with:
          cmd: yq -i '.name = "@mogeko/gatsby-remark-plantuml-lite"' 'package.json'
      - name: Setup registry url with GitHub Packages
        uses: actions/setup-node@v4.4.0
        with:
          registry-url: https://npm.pkg.github.com
          node-version-file: package.json
          scope: "@mogeko"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
